from enum import Enum, IntEnum

class Resource(IntEnum):
    NOTHING = 0
    METAL = 1
    OIL = 2
    URANIUM = 3
    POLYMER = 4
    SILICON = 5
    AEROGEL = 6
    WATER = 7
    BERILLYUM = 8
    PLUTONIUM = 9
    GOLD = 10
    EXOTIC_ICE = 11
    DIAMOND = 12
    XENON = 13
    ANTIHYDROGEN = 14
    MOON_ROCK = 15
    OBSIDIAN_SHARD = 16
    ALIEN_ARTIFACT = 17
    METALLIC_HYDROGEN = 18
    TUNA_CASSAROLE = 19
    DEBRIS = 20
    CARBON_FIBER = 21
    MESHUGGATRON = 22
    DARK_MATTER = 23
    QUANTUM_DUST = 24
    NEBULA_GAS = 25
    OORT_ICE = 26
    TRANSPARENT_ALUMINUM = 27
    PLATINUM = 28
    

    

