from enum import Enum, IntEnum

class Components(IntEnum):
    UNDEFINED = 0
    STANDARD_HULL = 1
    MEDIUM_FAIRING = 2
    COMMUNICATIONS_SATELLITE = 3
    STANDARD_THRUSTER = 4
    HYDER_THRUSTER = 5
    ECO_THRUSTER = 6
    FLASH_BOOSTER = 7
    AUX_BOOSTER_L = 8
    AUX_BOOSTER_R = 9
    REVERSIBLE_THRUSTER = 10

