from enum import Enum, IntEnum

class Components(IntEnum):
    UNDEFINED = 0
    STANDARD_HULL = 1
    MEDIUM_FAIRING = 2
    COMMUNICATIONS_SATELLITE = 3
    STANDARD_THRUSTER = 4
    HYDER_THRUSTER = 5
    ECO_THRUSTER = 6
    FLASH_BOOSTER = 7
    AUX_BOOSTER_L = 8
    AUX_BOOSTER_R = 9
    REVERSIBLE_THRUSTER = 10
    PROBE = 11
    FLDSMDFR = 12
    SPACE_TELESCOPE = 13
    LIGHT_HULL = 14
    HEAVY_HULL = 15
    VERTICAL_STAGE_SEPERATOR = 16
    HORIZONTAL_STAGE_SEPERATOR = 17
    THERMAL_PLATE = 18
    TEMPERATURE_REGULATOR = 19
    BATTERY_PACK = 20
    AERODYNAMIC_NOSE_CONE = 21
    SOLAR_PANEL = 22
    NUCLEAR_REACTOR = 23
    LUNAR_LANDER_F = 24
    LUNAR_LANDER_P = 25
    SPACE_SHUTTLE = 26